"""empty message

Revision ID: 36c72eaaf8f0
Revises: 465e407db3ac
Create Date: 2024-09-12 22:14:35.897258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c72eaaf8f0'
down_revision = '465e407db3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ShowTimeID', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'showtime', ['ShowTimeID'], ['id'])
        batch_op.drop_column('ShowTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ShowTime', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'showtime', ['ShowTime'], ['id'])
        batch_op.drop_column('ShowTimeID')

    # ### end Alembic commands ###
